### ISSUE TITLE
Unclear websocket documentation.

### ISSUE THREAD

**Issue by jackn11** [GenieFramework/GenieAuthentication.jl#18]
It is my understanding that on the page https://genieframework.github.io/Genie.jl/dev/tutorials/17--Working_with_Web_Sockets.html, in the, Pushing messages from the server section, the two underscores in this line ```We have one connected client to the __ channel! We can send it a message:``` refers to the two underscores in the output displayed above, ``` Genie.WebChannels.ChannelClient(HTTP.WebSockets.WebSocket{HTTP.ConnectionPool.Transaction{Sockets.TCPSocket}}(T0  🔁    0↑🔒    0↓🔒 100s 127.0.0.1:8001:8001 ≣16, 0x01, true, UInt8[0x7b, 0x22, 0x63, 0x68, 0x61, 0x6e, 0x6e, 0x65, 0x6c, 0x22  …  0x79, 0x6c, 0x6f, 0x61, 0x64, 0x22, 0x3a, 0x7b, 0x7d, 0x7d], UInt8[], false, false), ["__"])```. However, in my repl, I got 4 underscores. As there is no explanation as to where these two underscores are coming from, it could be unclear to people that they should check to see how many underscores to include if, like me, it is not the same number of underscores as is shown in the documentation.

**Comment by essenciary** [comment]
I'm not sure why this is here as it's not related to GenieAuthentication. Also, we talked about this in a different context and clarified it, so I'm going to close this one.
