### ISSUE TITLE
[error | LibPQ]: UndefinedTable: ERROR:  relation "schema_migrations" does not exist

### ISSUE THREAD

**Issue by deahhh** [GenieFramework/GenieAuthentication.jl#20]
After creating a app with code `Genie.Generator.newapp_mvc`, I execute some code guided by [mainpage](https://juliahub.com/ui/Packages/GenieAuthentication/Z5k6Z/2.2.0).

Then, I met the error `relation "schema_migrations" does not exist` after executing `SearchLight.Migration.up("CreateTableUsers")`.

My database is postgreSQL，empty, connected correctly.

Help, please!

**Comment by essenciary** [comment]
You need to run `SearchLight.Migrations.init()` first, to set up the migrations table.

**Comment by deahhh** [comment]
Thanks!
I should read more carefully.
