### ISSUE TITLE
current_user() is not defined

### ISSUE THREAD

**Issue by alerem18** [GenieFramework/GenieAuthentication.jl#22]
can't use it anywhere, also read the source code and there is no method current_user()

**Comment by essenciary** [comment]
Have you successfully followed the installation instructions? Are you correctly loading the plugin?

**Comment by alerem18** [comment]
> Have you successfully followed the installation instructions? Are you correctly loading the plugin?

yes, and where is the current_user implementation in source code?

**Comment by essenciary** [comment]
Once you correctly install the plugin, you will have a `plugins/genie_autentication.jl` file in your app. That's where it is.

**Comment by alerem18** [comment]
yes i see it but i've installed the plugin succuessfully

**Comment by essenciary** [comment]
Can you share your app?

**Comment by alerem18** [comment]
> Can you share your app?

i can just redefine current_user in my code but i wonder it's not working now
https://github.com/alerem18/Uploader

**Comment by essenciary** [comment]
@alerem18 seems to work fine. It looks like you haven't required the authentication: 
![CleanShot 2023-06-12 at 18 58 07@2x](https://github.com/GenieFramework/GenieAuthentication.jl/assets/11292378/a805fc65-3145-4c78-ab08-2671c25264b1)

**Comment by alerem18** [comment]
i did it on purpose by the way, i used authenticated() instead to handle my custom logic, but it wasn't working for me idk why
